# Site settings
title: Planning Factory
email: service@planning-factory.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Planning Factory
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://docs.planning-factory.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "*.json", "app.*", "Gulpfile.js"]
